name: GitHub Pages Deploy

on:
  push:
    branches:
      - main # push를 감지할 대상 branch 입니다.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        env:
          Environment_variables: ${{ secrets.TEST_VARIABLE_NAME }}
          Environment_secrets: ${{ secrets.TEST_SECRETS_NAME }}
          NEXT_PUBLIC_TEST_VARIABLE: ${{ secrets.TEST_VARIABLE_NAME }}
          NEXT_PUBLIC_TEST_SECRET: ${{ secrets.TEST_SECRETS_NAME }}
        run: |
          npm install
          npm run build && touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # github page를 서비스 할 branch 입니다.
          folder: out
